custom: ['https://saweria.co/satyakresna', 'https://trakteer.id/satyakresna']

community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: # Replace with a single Open Collective username
otechie: # Replace with a single Otechie username
patreon: # Replace with a single Patreon username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel